"""SQL auto-correction for LLM-generated report queries.

Extracted from services.report_generator. Pure regex/string rewriting that
fixes common SQL mistakes the LLM makes (wrong table/alias references,
missing joins, broken GROUP BY clauses, etc.). No project deps.
"""

import logging
import re

logger = logging.getLogger(__name__)

# ── SQL Auto-Correction ────────────────────────────────────────────────────
# The LLM persistently treats sales_order_line_pricing as if it were a
# combined sales_order + sales_order_line table. It references columns like
# status, so_id, product_id on the pricing table, but those columns live on
# sales_order and sales_order_line respectively.
#
# This auto-corrector detects and rewrites these broken queries.

# Columns that belong to sales_order (NOT on line/pricing/gold/diamond)
_SO_ONLY_COLS = {'status', 'so_id', 'customer_id', 'order_date', 'total_amount',
                 'order_number', 'created_at', 'updated_at'}
# Columns that belong to sales_order_line (NOT pricing/gold/diamond)
_SOL_ONLY_COLS = {'product_id', 'variant_sku', 'quantity', 'so_id'}
# Sub-tables that are frequently misused as main FROM tables
_SUB_TABLES = {
    'sales_order_line_pricing': 'solp',
    'sales_order_line_gold': 'solg',
    'sales_order_line_diamond': 'sold',
}


def _fix_report_sql(sql: str) -> str:
    """Auto-correct common SQL mistakes generated by the LLM.

    Handles multiple error patterns:
    1. Sub-tables (pricing/gold/diamond) used as FROM with wrong column refs
    2. sales_order joined directly to product_master (missing sales_order_line)
    3. so.product_id references (product_id lives on sales_order_line, not sales_order)
    """
    if not sql:
        return sql

    original = sql

    # Strip SQL comments BEFORE collapsing whitespace.
    # If we collapse first, '-- comment\nWITH ...' becomes '-- comment WITH ...'
    # which is a single-line comment that swallows the entire query.
    sql = re.sub(r'--[^\n]*', '', sql)          # strip -- line comments
    sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)  # strip /* block */ comments

    # Normalize whitespace for easier matching
    sql_oneline = ' '.join(sql.split())

    # ══════════════════════════════════════════════════════════════════════
    # PASS 0: Auto-fix GROUP BY with AS aliases or aggregate keywords.
    #
    # Claude Haiku frequently writes broken GROUP BY clauses like:
    #   GROUP BY so.order_type AS label, ROUND(SUM(...)), AS, revenue
    #   GROUP BY territory_id, SUM, total_amount, AS, revenue
    #   GROUP BY territory_id, SUM(total_amount) rev  <- bare alias, still broken
    #
    # Strategy per comma-separated GROUP BY item:
    #   1. Strip any trailing  AS <alias>
    #   2. Drop item if it is a bare SQL keyword (AS, SUM, DISTINCT, …)
    #   3. Drop item if it starts with an aggregate function call SUM(…), ROUND(…)…
    # ══════════════════════════════════════════════════════════════════════
    _AGG_FUNCS_P0 = re.compile(
        r'^\s*(SUM|COUNT|AVG|MIN|MAX|ROUND|COALESCE|NULLIF|CAST|ABS)\s*\(',
        re.IGNORECASE
    )
    _BARE_KW_P0 = re.compile(
        r'^\s*(SUM|COUNT|AVG|MIN|MAX|ROUND|DISTINCT|COALESCE|NULLIF|AS)\s*$',
        re.IGNORECASE
    )

    def _split_top_level(text: str) -> list:
        """Split text on top-level commas (not inside parentheses)."""
        items, depth, buf = [], 0, []
        for ch in text:
            if ch == '(':
                depth += 1; buf.append(ch)
            elif ch == ')':
                depth -= 1; buf.append(ch)
            elif ch == ',' and depth == 0:
                items.append(''.join(buf)); buf = []
            else:
                buf.append(ch)
        if buf:
            items.append(''.join(buf))
        return items

    def _clean_gb_items(gb_body: str) -> str | None:
        """Clean GROUP BY item list; return None if nothing changed."""
        items = _split_top_level(gb_body)
        cleaned = []
        changed = False
        for raw in items:
            item = raw.strip()
            if not item:
                changed = True; continue
            # Drop bare SQL keywords
            if _BARE_KW_P0.match(item):
                changed = True; continue
            # Drop aggregate function calls
            if _AGG_FUNCS_P0.match(item):
                changed = True; continue
            # Strip trailing AS <alias>
            stripped = re.sub(r'\s+AS\s+\w+\s*$', '', item, flags=re.IGNORECASE).strip()
            if stripped != item:
                changed = True
                item = stripped
            # After stripping alias, item might now be an aggregate
            if _AGG_FUNCS_P0.match(item):
                changed = True; continue
            cleaned.append(item)
        if not changed:
            return None
        return ', '.join(cleaned) if cleaned else None

    # Locate every GROUP BY … end-of-clause span and collect replacements.
    # We search forward from gb_match.end() to find where the GROUP BY body ends,
    # then replace only that span.  We collect all replacements and apply them
    # right-to-left so earlier indices stay valid.
    _gb_pattern = re.compile(r'\bGROUP\s+BY\b', re.IGNORECASE)
    _terminator = re.compile(
        r'(?:\b(?:ORDER\s+BY|HAVING|LIMIT|UNION|EXCEPT|INTERSECT)\b|\))',
        re.IGNORECASE
    )

    replacements = []  # list of (start, end, new_text)
    for gb_match in _gb_pattern.finditer(sql_oneline):
        body_start = gb_match.end()
        tail = sql_oneline[body_start:]
        term = _terminator.search(tail)
        if term:
            gb_body = tail[:term.start()]
            body_end = body_start + term.start()
        else:
            gb_body = tail
            body_end = len(sql_oneline)
        cleaned = _clean_gb_items(gb_body)
        if cleaned is not None:
            logger.info(
                "[SQL auto-correct PASS 0] Fixed GROUP BY:\n  BEFORE: GROUP BY%s\n  AFTER:  GROUP BY %s",
                gb_body[:200], cleaned[:200]
            )
            replacements.append((gb_match.start(), body_end, 'GROUP BY ' + cleaned))

    # Apply right-to-left so earlier spans aren't shifted
    for start, end, new_text in sorted(replacements, key=lambda x: -x[0]):
        sql_oneline = sql_oneline[:start] + new_text + sql_oneline[end:]

    # ══════════════════════════════════════════════════════════════════════
    # PASS 1: Fix sub-table (pricing/gold/diamond) alias issues
    # ══════════════════════════════════════════════════════════════════════
    for sub_tbl, preferred_alias in _SUB_TABLES.items():
        # Find the alias used for this sub-table
        alias_match = re.search(
            rf'\b{sub_tbl}\s+(\w+)\b', sql_oneline, re.IGNORECASE
        )
        if not alias_match:
            continue

        alias = alias_match.group(1)

        # Check if this alias references columns it doesn't own (aliased refs)
        has_status_ref = bool(re.search(rf'\b{re.escape(alias)}\.status\b', sql_oneline, re.IGNORECASE))
        has_so_id_ref = bool(re.search(rf'\b{re.escape(alias)}\.so_id\b', sql_oneline, re.IGNORECASE))
        has_product_id_ref = bool(re.search(rf'\b{re.escape(alias)}\.product_id\b', sql_oneline, re.IGNORECASE))
        has_customer_id_ref = bool(re.search(rf'\b{re.escape(alias)}\.customer_id\b', sql_oneline, re.IGNORECASE))
        has_order_date_ref = bool(re.search(rf'\b{re.escape(alias)}\.order_date\b', sql_oneline, re.IGNORECASE))
        has_quantity_ref = bool(re.search(rf'\b{re.escape(alias)}\.quantity\b', sql_oneline, re.IGNORECASE))
        has_variant_sku_ref = bool(re.search(rf'\b{re.escape(alias)}\.variant_sku\b', sql_oneline, re.IGNORECASE))
        has_total_amount_ref = bool(re.search(rf'\b{re.escape(alias)}\.total_amount\b', sql_oneline, re.IGNORECASE))

        # Also detect UNPREFIXED column references — the LLM sometimes writes
        # "SELECT product_id FROM sales_order_line_pricing WHERE status = 'closed'"
        # without any alias prefix. These bare columns are wrong if the sub-table
        # doesn't own them.
        is_from_table = bool(re.search(rf'\bFROM\s+{sub_tbl}\b', sql_oneline, re.IGNORECASE))
        if is_from_table:
            # Check for bare (unprefixed) column references
            for col in ('status', 'order_date', 'customer_id', 'total_amount'):
                if not has_status_ref and col == 'status' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_status_ref = True
                if not has_order_date_ref and col == 'order_date' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_order_date_ref = True
                if not has_customer_id_ref and col == 'customer_id' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_customer_id_ref = True
                if not has_total_amount_ref and col == 'total_amount' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_total_amount_ref = True
            for col in ('product_id', 'variant_sku', 'quantity'):
                if not has_product_id_ref and col == 'product_id' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_product_id_ref = True
                if not has_variant_sku_ref and col == 'variant_sku' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_variant_sku_ref = True
                if not has_quantity_ref and col == 'quantity' and re.search(rf'(?<!\w\.)\b{col}\b', sql_oneline, re.IGNORECASE):
                    has_quantity_ref = True

        needs_sol = has_so_id_ref or has_product_id_ref or has_quantity_ref or has_variant_sku_ref
        needs_so = has_status_ref or has_customer_id_ref or has_order_date_ref or has_total_amount_ref

        if not needs_sol and not needs_so:
            continue

        logger.info(
            "SQL auto-correct: %s alias '%s' references wrong columns "
            "(status=%s, so_id=%s, product_id=%s). Injecting proper joins.",
            sub_tbl, alias, has_status_ref, has_so_id_ref, has_product_id_ref
        )

        # Check what tables are already in the query
        stripped = sql_oneline
        for t in _SUB_TABLES:
            stripped = stripped.replace(t, '')
        has_sol_table = 'sales_order_line' in stripped.replace('sales_order_line_', '')
        has_so_table = bool(re.search(r'\bsales_order\b(?!_)', stripped))

        # Choose alias names that won't conflict
        sol_alias = 'sol' if alias != 'sol' else 'sol2'
        so_alias = 'so' if alias != 'so' else 'so2'

        # Restructure the FROM clause
        from_pattern = re.compile(
            rf'FROM\s+{sub_tbl}\s+{re.escape(alias)}\b',
            re.IGNORECASE
        )
        if from_pattern.search(sql_oneline):
            new_from = f'FROM sales_order {so_alias}'
            new_from += f' JOIN sales_order_line {sol_alias} ON {so_alias}.so_id = {sol_alias}.so_id'
            new_from += f' JOIN {sub_tbl} {alias} ON {sol_alias}.sol_id = {alias}.sol_id'
            sql_oneline = from_pattern.sub(new_from, sql_oneline, count=1)

            # Remove any now-redundant JOIN to sales_order
            sql_oneline = re.sub(
                rf'\bJOIN\s+sales_order\s+{re.escape(so_alias)}\s+ON\s+[^J]*?(?=JOIN|\bWHERE\b|\bGROUP\b|\bORDER\b|\bLIMIT\b|$)',
                '', sql_oneline, flags=re.IGNORECASE
            )
            has_sol_table = True
            has_so_table = True
        else:
            # Sub-table is joined, not FROM — inject missing intermediate tables
            if needs_sol and not has_sol_table:
                sql_oneline = re.sub(
                    rf'JOIN\s+{sub_tbl}\s+{re.escape(alias)}\b',
                    f'JOIN sales_order_line {sol_alias} ON {sol_alias}.so_id = {so_alias}.so_id '
                    f'JOIN {sub_tbl} {alias}',
                    sql_oneline, count=1, flags=re.IGNORECASE
                )
                sql_oneline = re.sub(
                    rf'JOIN\s+{sub_tbl}\s+{re.escape(alias)}\s+ON\s+\w+\.so_id\s*=\s*{re.escape(alias)}\.so_id',
                    f'JOIN {sub_tbl} {alias} ON {sol_alias}.sol_id = {alias}.sol_id',
                    sql_oneline, flags=re.IGNORECASE
                )
                has_sol_table = True

            if needs_so and not has_so_table:
                sql_oneline = re.sub(
                    r'\bFROM\b',
                    f'FROM sales_order {so_alias} JOIN',
                    sql_oneline, count=1, flags=re.IGNORECASE
                )
                has_so_table = True

        # Remap column references to correct aliases
        if has_status_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.status\b',
                f'{so_alias}.status',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_so_id_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.so_id\b',
                f'{sol_alias}.so_id',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_product_id_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.product_id\b',
                f'{sol_alias}.product_id',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_customer_id_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.customer_id\b',
                f'{so_alias}.customer_id',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_order_date_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.order_date\b',
                f'{so_alias}.order_date',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_total_amount_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.total_amount\b',
                f'{so_alias}.total_amount',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_quantity_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.quantity\b',
                f'{sol_alias}.quantity',
                sql_oneline, flags=re.IGNORECASE
            )
        if has_variant_sku_ref:
            sql_oneline = re.sub(
                rf'\b{re.escape(alias)}\.variant_sku\b',
                f'{sol_alias}.variant_sku',
                sql_oneline, flags=re.IGNORECASE
            )

        # Remap UNPREFIXED (bare) column references to correct aliases
        # e.g., "WHERE status = 'closed'" → "WHERE so.status = 'closed'"
        if is_from_table:
            bare_so_cols = {'status': so_alias, 'order_date': so_alias,
                           'customer_id': so_alias, 'total_amount': so_alias}
            bare_sol_cols = {'product_id': sol_alias, 'variant_sku': sol_alias,
                            'quantity': sol_alias}
            for col, target_alias in {**bare_so_cols, **bare_sol_cols}.items():
                # Match bare column NOT preceded by a dot (i.e., not already aliased)
                sql_oneline = re.sub(
                    rf'(?<!\w\.)(?<!\w)\b{col}\b(?!\s*\()',  # avoid function names
                    f'{target_alias}.{col}',
                    sql_oneline, flags=re.IGNORECASE
                )
    # ══════════════════════════════════════════════════════════════════════
    # PASS 2: Fix so.product_id → sol.product_id  (product_id lives on
    #         sales_order_line, NOT sales_order)
    # ══════════════════════════════════════════════════════════════════════

    # Find all aliases used for sales_order (but NOT sales_order_line*)
    so_aliases = set()
    for m in re.finditer(r'\bsales_order\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE):
        so_aliases.add(m.group(1))

    for so_alias in so_aliases:
        if not re.search(rf'\b{re.escape(so_alias)}\.product_id\b', sql_oneline, re.IGNORECASE):
            continue

        logger.info("SQL auto-correct: %s.product_id detected — product_id is on sales_order_line, not sales_order", so_alias)

        # Find the alias for sales_order_line if it exists
        sol_match = re.search(r'\bsales_order_line\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE)

        if sol_match:
            sol_alias = sol_match.group(1)
        else:
            # Need to inject sales_order_line into the query
            sol_alias = 'sol'
            # Insert JOIN sales_order_line after FROM sales_order so
            sql_oneline = re.sub(
                rf'(FROM\s+sales_order\s+{re.escape(so_alias)})\b',
                rf'\1 JOIN sales_order_line {sol_alias} ON {so_alias}.so_id = {sol_alias}.so_id',
                sql_oneline, count=1, flags=re.IGNORECASE
            )

        # Remap so.product_id → sol.product_id
        sql_oneline = re.sub(
            rf'\b{re.escape(so_alias)}\.product_id\b',
            f'{sol_alias}.product_id',
            sql_oneline, flags=re.IGNORECASE
        )

    # ══════════════════════════════════════════════════════════════════════
    # PASS 3: Fix direct sales_order → product_master JOIN (missing
    #         sales_order_line in between).
    #         Pattern: JOIN product_master pm ON so.product_id = pm.product_id
    #         Fix: inject sales_order_line, rewrite JOIN condition
    # ══════════════════════════════════════════════════════════════════════

    # Detect: JOIN product_master <alias> ON <so_alias>.product_id = <pm_alias>.product_id
    # where <so_alias> is a sales_order alias (already caught above, but joining might
    # still reference the wrong table).  After Pass 2, so.product_id is already fixed,
    # but we still need to ensure the JOIN to product_master goes through sol.
    # This is already handled by Pass 2 remapping, so no additional action needed
    # if Pass 2 ran.  But handle the case where the LLM omits sales_order_line entirely
    # and writes: FROM sales_order so JOIN product_master pm ON so.product_id = pm.product_id
    # (After Pass 2, this becomes sol.product_id, and the JOIN is already injected.)

    # ══════════════════════════════════════════════════════════════════════
    # PASS 4: Fix raw product_id / variant_sku used as a chart label column.
    #
    # The LLM sometimes writes:
    #   SELECT sol.product_id, SUM(...) AS value FROM ... GROUP BY sol.product_id
    # This produces SKU codes (PROD-0484) as labels instead of human-readable names.
    # Fix: inject JOIN to product_master and replace with pm.product_name.
    # ══════════════════════════════════════════════════════════════════════

    # Detect sol.<alias>.product_id or sol.variant_sku as first SELECT token
    _sol_alias_m = re.search(r'\bsales_order_line\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE)
    _sol_alias_p4 = _sol_alias_m.group(1) if _sol_alias_m else 'sol'

    # Check: does the SELECT clause start with <sol_alias>.product_id or .variant_sku?
    _select_label_pid = re.search(
        rf'\bSELECT\s+{re.escape(_sol_alias_p4)}\.(product_id|variant_sku)\b',
        sql_oneline, re.IGNORECASE
    )
    if _select_label_pid:
        logger.info(
            "SQL auto-correct PASS 4: %s.%s used as chart label — rewriting to pm.product_name",
            _sol_alias_p4, _select_label_pid.group(1)
        )
        # Check if product_master is already joined
        _has_pm = bool(re.search(r'\bproduct_master\b', sql_oneline, re.IGNORECASE))
        _pm_alias = 'pm'
        if not _has_pm:
            # Find a good place to inject: after the last JOIN or after FROM clause
            # Inject before WHERE / GROUP / ORDER / LIMIT
            _inject_point = re.search(
                r'\b(WHERE|GROUP\s+BY|ORDER\s+BY|LIMIT)\b', sql_oneline, re.IGNORECASE
            )
            if _inject_point:
                pos = _inject_point.start()
                sql_oneline = (
                    sql_oneline[:pos]
                    + f'JOIN product_master {_pm_alias} ON {_sol_alias_p4}.product_id = {_pm_alias}.product_id '
                    + sql_oneline[pos:]
                )
            else:
                sql_oneline += f' JOIN product_master {_pm_alias} ON {_sol_alias_p4}.product_id = {_pm_alias}.product_id'
        else:
            # Find the pm alias already in use
            _pm_alias_m = re.search(r'\bproduct_master\s+(\w+)', sql_oneline, re.IGNORECASE)
            if _pm_alias_m:
                _pm_alias = _pm_alias_m.group(1)

        # Replace the label column in SELECT
        sql_oneline = re.sub(
            rf'\bSELECT\s+{re.escape(_sol_alias_p4)}\.(product_id|variant_sku)\b',
            f'SELECT {_pm_alias}.product_name',
            sql_oneline, count=1, flags=re.IGNORECASE
        )
        # Replace in GROUP BY
        sql_oneline = re.sub(
            rf'\bGROUP\s+BY\s+{re.escape(_sol_alias_p4)}\.(product_id|variant_sku)\b',
            f'GROUP BY {_pm_alias}.product_name',
            sql_oneline, flags=re.IGNORECASE
        )

    # ══════════════════════════════════════════════════════════════════════
    # PASS 5: Fix raw customer_id used as chart label → customer_name
    #
    # The LLM sometimes writes:
    #   SELECT so.customer_id, SUM(...) AS value FROM ... GROUP BY so.customer_id
    # This produces raw IDs (C001) as labels instead of human-readable names.
    # Fix: inject JOIN to customer_master and replace with cm.customer_name.
    # ══════════════════════════════════════════════════════════════════════

    _SQL_KEYWORDS = {'WHERE', 'GROUP', 'ORDER', 'LIMIT', 'JOIN', 'ON', 'LEFT',
                     'RIGHT', 'INNER', 'HAVING', 'UNION', 'AS', 'SET', 'INTO',
                     'VALUES', 'SELECT', 'FROM', 'AND', 'OR', 'NOT', 'IN',
                     'CROSS', 'FULL', 'OUTER', 'NATURAL', 'USING', 'BETWEEN'}

    _so_alias_m = re.search(r'\bsales_order\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE)
    _so_alias_p5 = _so_alias_m.group(1) if _so_alias_m else None
    # Guard: if the captured "alias" is actually a SQL keyword, there's no real alias
    if _so_alias_p5 and _so_alias_p5.upper() in _SQL_KEYWORDS:
        _so_alias_p5 = None
    # Use the table name directly when no alias is present
    _so_ref_p5 = _so_alias_p5 if _so_alias_p5 else 'sales_order'

    # Check: does the SELECT clause contain <so_alias>.customer_id as a label?
    _select_label_cid = re.search(
        rf'\bSELECT\s+{re.escape(_so_ref_p5)}\.customer_id\b',
        sql_oneline, re.IGNORECASE
    )
    # Also check for bare customer_id (no alias prefix)
    if not _select_label_cid:
        _select_label_cid = re.search(
            r'\bSELECT\s+customer_id\b',
            sql_oneline, re.IGNORECASE
        )

    if _select_label_cid:
        logger.info("SQL auto-correct PASS 5: customer_id as chart label — customer_master not in schema, skipping rewrite")

    # ══════════════════════════════════════════════════════════════════════
    # PASS 6: Fix raw vendor_id used as chart label → vendor_name
    # ══════════════════════════════════════════════════════════════════════

    _po_alias_m = re.search(r'\bpurchase_order\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE)
    _po_alias_p6 = _po_alias_m.group(1) if _po_alias_m else None
    if _po_alias_p6 and _po_alias_p6.upper() in _SQL_KEYWORDS:
        _po_alias_p6 = None
    _po_ref_p6 = _po_alias_p6 if _po_alias_p6 else 'purchase_order'

    _select_label_vid = re.search(
        rf'\bSELECT\s+(?:{re.escape(_po_ref_p6)}\.)?vendor_id\b',
        sql_oneline, re.IGNORECASE
    )
    if _select_label_vid:
        logger.info("SQL auto-correct PASS 6: vendor_id used as chart label — rewriting to vm.vendor_name")
        _has_vm = bool(re.search(r'\bvendor_master\b', sql_oneline, re.IGNORECASE))
        _vm_alias = 'vm'
        if not _has_vm:
            _inject_point = re.search(
                r'\b(WHERE|GROUP\s+BY|ORDER\s+BY|LIMIT)\b', sql_oneline, re.IGNORECASE
            )
            if _inject_point:
                pos = _inject_point.start()
                sql_oneline = (
                    sql_oneline[:pos]
                    + f'JOIN vendor_master {_vm_alias} ON {_po_ref_p6}.vendor_id = {_vm_alias}.vendor_id '
                    + sql_oneline[pos:]
                )
            else:
                sql_oneline += f' JOIN vendor_master {_vm_alias} ON {_po_ref_p6}.vendor_id = {_vm_alias}.vendor_id'
        else:
            _vm_alias_m = re.search(r'\bvendor_master\s+(\w+)', sql_oneline, re.IGNORECASE)
            if _vm_alias_m:
                _vm_alias = _vm_alias_m.group(1)

        sql_oneline = re.sub(
            rf'\bSELECT\s+(?:{re.escape(_po_ref_p6)}\.)?vendor_id\b',
            f'SELECT {_vm_alias}.vendor_name',
            sql_oneline, count=1, flags=re.IGNORECASE
        )
        sql_oneline = re.sub(
            rf'\bGROUP\s+BY\s+(?:{re.escape(_po_ref_p6)}\.)?vendor_id\b',
            f'GROUP BY {_vm_alias}.vendor_name',
            sql_oneline, flags=re.IGNORECASE
        )

    # ══════════════════════════════════════════════════════════════════════
    # PASS 7: Fix gold/diamond-specific columns referenced on wrong alias.
    #
    # gold_kt, gold_purity, gold_weight_grams  → sales_order_line_gold  (NOT pricing)
    # diamond_type, diamond_carat, diamond_quality, diamond_color → sales_order_line_diamond
    #
    # The LLM writes lp.gold_kt or solp.gold_kt — both fail at DB level.
    # Postgres HINT: "Perhaps you meant to reference the column 'g.gold_kt'."
    # ══════════════════════════════════════════════════════════════════════

    _GOLD_ONLY_COLS7 = ('gold_kt', 'gold_purity', 'gold_weight_grams')
    _DIAMOND_ONLY_COLS7 = ('diamond_type', 'diamond_carat', 'diamond_quality', 'diamond_color')

    # Detect current gold / diamond / sol table aliases
    _solg_m7 = re.search(r'\bsales_order_line_gold\s+(\w+)', sql_oneline, re.IGNORECASE)
    _solg_alias7 = _solg_m7.group(1) if _solg_m7 else None
    _sold_m7 = re.search(r'\bsales_order_line_diamond\s+(\w+)', sql_oneline, re.IGNORECASE)
    _sold_alias7 = _sold_m7.group(1) if _sold_m7 else None
    _sol_m7 = re.search(r'\bsales_order_line\b(?!_)\s+(\w+)', sql_oneline, re.IGNORECASE)
    _sol_alias7 = _sol_m7.group(1) if _sol_m7 else 'sol'

    for _gcol in _GOLD_ONLY_COLS7:
        _bad_gold_refs = re.findall(rf'\b(\w+)\.{_gcol}\b', sql_oneline, re.IGNORECASE)
        for _bad_a in set(_bad_gold_refs):
            if _solg_alias7 and _bad_a.lower() == _solg_alias7.lower():
                continue  # already on the correct gold table alias
            if _solg_alias7:
                sql_oneline = re.sub(
                    rf'\b{re.escape(_bad_a)}\.{_gcol}\b',
                    f'{_solg_alias7}.{_gcol}',
                    sql_oneline, flags=re.IGNORECASE
                )
                logger.info("SQL auto-correct PASS 7: %s.%s → %s.%s (gold column on wrong alias)",
                            _bad_a, _gcol, _solg_alias7, _gcol)
            else:
                _solg_alias7 = 'solg'
                _inj7 = re.search(r'\b(WHERE|GROUP\s+BY|ORDER\s+BY|LIMIT)\b', sql_oneline, re.IGNORECASE)
                _join7 = f'JOIN sales_order_line_gold {_solg_alias7} ON {_sol_alias7}.sol_id = {_solg_alias7}.sol_id '
                if _inj7:
                    pos = _inj7.start()
                    sql_oneline = sql_oneline[:pos] + _join7 + sql_oneline[pos:]
                else:
                    sql_oneline += ' ' + _join7.strip()
                sql_oneline = re.sub(
                    rf'\b{re.escape(_bad_a)}\.{_gcol}\b',
                    f'{_solg_alias7}.{_gcol}',
                    sql_oneline, flags=re.IGNORECASE
                )
                logger.info("SQL auto-correct PASS 7: added gold join + fixed %s.%s → %s.%s",
                            _bad_a, _gcol, _solg_alias7, _gcol)

    for _dcol in _DIAMOND_ONLY_COLS7:
        _bad_dia_refs = re.findall(rf'\b(\w+)\.{_dcol}\b', sql_oneline, re.IGNORECASE)
        for _bad_a in set(_bad_dia_refs):
            if _sold_alias7 and _bad_a.lower() == _sold_alias7.lower():
                continue
            if _sold_alias7:
                sql_oneline = re.sub(
                    rf'\b{re.escape(_bad_a)}\.{_dcol}\b',
                    f'{_sold_alias7}.{_dcol}',
                    sql_oneline, flags=re.IGNORECASE
                )
                logger.info("SQL auto-correct PASS 7: %s.%s → %s.%s (diamond column on wrong alias)",
                            _bad_a, _dcol, _sold_alias7, _dcol)
            else:
                _sold_alias7 = 'sold'
                _inj7 = re.search(r'\b(WHERE|GROUP\s+BY|ORDER\s+BY|LIMIT)\b', sql_oneline, re.IGNORECASE)
                _join7 = f'JOIN sales_order_line_diamond {_sold_alias7} ON {_sol_alias7}.sol_id = {_sold_alias7}.sol_id '
                if _inj7:
                    pos = _inj7.start()
                    sql_oneline = sql_oneline[:pos] + _join7 + sql_oneline[pos:]
                else:
                    sql_oneline += ' ' + _join7.strip()
                sql_oneline = re.sub(
                    rf'\b{re.escape(_bad_a)}\.{_dcol}\b',
                    f'{_sold_alias7}.{_dcol}',
                    sql_oneline, flags=re.IGNORECASE
                )
                logger.info("SQL auto-correct PASS 7: added diamond join + fixed %s.%s → %s.%s",
                            _bad_a, _dcol, _sold_alias7, _dcol)

    sql = sql_oneline

    # PASS 8 removed — it incorrectly tokenized aggregate expressions like
    # SUM(total_amount) AS revenue and added SUM, AS, revenue as GROUP BY items.
    # PASS 0 handles GROUP BY cleanup correctly.

    # ══════════════════════════════════════════════════════════════════════
    # PASS 9: Auto-fix duplicate table aliases
    # If same alias is used for different tables, rename subsequent uses
    # ══════════════════════════════════════════════════════════════════════

    _from_matches9 = re.findall(r'\bFROM\s+(\w+)\s+(\w+)', sql, re.IGNORECASE)
    _join_matches9 = re.findall(r'\bJOIN\s+(\w+)\s+(\w+)', sql, re.IGNORECASE)

    _alias_map9 = {}
    _alias_conflicts9 = []

    for _table9, _alias9 in _from_matches9 + _join_matches9:
        _alias_lower9 = _alias9.lower()
        if _alias_lower9 in _alias_map9:
            # Same alias used for different tables
            if _alias_map9[_alias_lower9] != _table9:
                _alias_conflicts9.append((_table9, _alias9, _alias_map9[_alias_lower9]))
        else:
            _alias_map9[_alias_lower9] = _table9

    for _table9, _alias9, _first_table9 in _alias_conflicts9:
        # Generate a new unique alias
        _base9 = _alias9.rstrip('0123456789')
        _counter9 = 2
        _new_alias9 = f"{_base9}{_counter9}"
        while _new_alias9.lower() in _alias_map9:
            _counter9 += 1
            _new_alias9 = f"{_base9}{_counter9}"

        # Replace the conflicting alias (second occurrence only)
        _pattern9 = rf'(FROM\s+{_table9}\s+){_alias9}\b'
        if not re.search(_pattern9, sql, re.IGNORECASE):
            _pattern9 = rf'(JOIN\s+{_table9}\s+){_alias9}\b'

        _sql_before9 = sql
        sql = re.sub(_pattern9, rf'\g<1>{_new_alias9}', sql, count=1, flags=re.IGNORECASE)

        if sql != _sql_before9:
            logger.info("SQL auto-correct PASS 9: Renamed duplicate alias '%s' → '%s' for table '%s'",
                       _alias9, _new_alias9, _table9)

    if sql != original:
        logger.info("SQL auto-corrected:\n  BEFORE: %s\n  AFTER:  %s",
                     original.replace('\n', ' ')[:300],
                     sql[:300])

    return sql
